export function page() { return `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PhoneHaul Receiver</title>
<style>
:root{font-family:system-ui,sans-serif;color:#172b2a;background:#f4f7f4}body{max-width:620px;margin:4rem auto;padding:0 1.2rem}h1{font-size:2.1rem;margin-bottom:.2rem}.tag{color:#526763;margin-top:0}.card{background:#fff;border:1px solid #dce6e0;border-radius:18px;padding:1.5rem;margin:1rem 0;box-shadow:0 8px 30px #133a2410}#qr{display:block;width:240px;height:240px;margin:1.5rem auto}button{border:0;border-radius:9px;background:#08765f;color:#fff;padding:.8rem 1rem;font:inherit;cursor:pointer}button.secondary{background:#dfeae4;color:#173b31}input,select{font:inherit;padding:.7rem;border:1px solid #bacac2;border-radius:8px;max-width:100%;box-sizing:border-box}input{width:100%}label{display:block;margin:.8rem 0}.muted{color:#61736d}progress{width:100%;height:1.2rem}#error{color:#a32520}#settings{display:none}.row{display:flex;gap:.6rem;align-items:center;flex-wrap:wrap}code{overflow-wrap:anywhere}#drop{border:2px dashed #bacac2;border-radius:12px;padding:2rem;text-align:center;cursor:pointer;background:#f8fbf9;margin:1rem 0}#drop.dragging{border-color:#08765f;background:#e4f4ec}#sendFiles,#sendFolder{display:none}.sendItem{display:flex;justify-content:space-between;gap:.6rem;border-top:1px solid #e5ece7;padding:.6rem 0;align-items:center}.sendItem span:first-child{overflow-wrap:anywhere}.sendItem button{padding:.3rem .6rem}
</style>
<h1>PhoneHaul</h1><p class="tag">Scan. Select. Move.</p>
<section class="card"><h2 id="state">Ready to receive</h2><p id="description">Phone and computer must be connected to the same local network.</p><img id="qr" alt="Pairing QR code"><p id="pairText" class="muted">Scan this QR code with PhoneHaul on your Android phone. It refreshes automatically every five minutes until a phone connects.</p><p class="muted">Computer LAN address: <code id="lan"></code></p><button id="refresh" class="secondary">New QR</button></section>
<section class="card"><h2>Destination</h2><code id="destination"></code><p><button id="change" class="secondary">Change</button></p><div id="settings"><label>Destination folder<input id="folder"></label><label>When file already exists<select id="conflict"><option value="rename">Rename incoming file</option><option value="skip">Skip</option><option value="replace">Replace</option></select></label><button id="save">Save</button></div><p id="error"></p></section>
<section class="card"><h2>Send to phone</h2><p class="muted">Files go directly to Downloads on Android. Folder contents are placed together there.</p><div id="drop" role="button" tabindex="0">Drop files or folders here<br><span class="muted">or click to choose files</span></div><div class="row"><button id="chooseFiles" class="secondary">Select files</button><button id="chooseFolder" class="secondary">Select folder</button></div><input id="sendFiles" type="file" multiple><input id="sendFolder" type="file" webkitdirectory multiple><p id="sendStatus" class="muted">Waiting for phone connection.</p><div id="sendQueue"></div></section>
<section id="transfer" class="card" hidden><h2>Transfer</h2><p id="counts"></p><progress id="bar" max="100" value="0"></progress><p id="bytes"></p><p id="current"></p><p id="elapsed"></p><button id="cancel" class="secondary">Cancel</button></section>
<section id="recovery" class="card" hidden><h2>Incomplete transfers found</h2><p id="partials"></p><button id="removePartials" class="secondary">Remove partial files</button></section>
<script>
const $=id=>document.getElementById(id);let current=null,pairingVersion=null,sendItems=[],connected=false,localPending=[];
const fmt=n=>{if(n<1024)return n+' B';const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(1)+' '+u[i]};
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
async function load(){const s=await api('/api/ui');pairingVersion=s.pairingVersion;$('destination').textContent=s.settings.destination;$('folder').value=s.settings.destination;$('conflict').value=s.settings.conflict;$('qr').src=s.qr;$('qr').hidden=s.pairingComplete;$('lan').textContent=s.host+':'+s.port;$('refresh').hidden=s.connected;$('pairText').textContent=s.pairingComplete?(s.connected?'Phone paired. The QR code is hidden.':'Phone paired but not currently connected. Generate a new code to pair again.'):'Scan this QR code with PhoneHaul on your Android phone. It refreshes automatically every five minutes until a phone connects.';render(s.transfer,s.connected);renderSend(s.sendQueue,s.sendConnected,s.connected);$('recovery').hidden=!s.partials.length;$('partials').textContent=s.partials.length+' partial file(s) remain on disk.'}
function renderSend(items,online,phoneConnected=online){
 sendItems=items||[];connected=online;
 $('sendStatus').textContent=online?'Phone connected. Queued files send automatically.':phoneConnected?'This Android app cannot receive files. Update PhoneHaul on the phone.':'Waiting for phone connection. Added files will stay queued.';
 const root=$('sendQueue');root.replaceChildren();const all=[...localPending,...sendItems];
 for(const item of all){
  const row=document.createElement('div');row.className='sendItem';
  const name=document.createElement(item.type==='folder'?'strong':'span');const parts=item.relativePath.split('/');name.textContent=item.type==='folder'?item.relativePath:parts.at(-1)+(parts.length>1?' · from '+parts.slice(0,-1).join('/'):'');
  const state=document.createElement('span');const label=item.state==='sending'?'Sending '+Math.min(100,Math.floor(100*item.progress/(item.size||1)))+'%':item.state==='queued'&&!online?'Waiting for phone':item.state==='preparing'?'Adding to queue…':item.state+(item.error?' — '+item.error:'');state.textContent=(item.type==='folder'?item.fileCount+' files · ':'')+fmt(item.size)+' · '+label;
  row.append(name,state);
  if(item.id&&item.state==='queued'){const button=document.createElement('button');button.className='secondary';button.textContent='Remove';button.onclick=()=>fetch('/api/send/items/'+item.id,{method:'DELETE'}).then(()=>load()).catch(e=>$('error').textContent=e.message);row.append(button)}
  root.append(row)
 }
}
async function enqueueFiles(entries){for(const entry of entries){const pending={relativePath:entry.relativePath,size:entry.file.size,state:'preparing'};localPending.push(pending);renderSend(sendItems,connected);try{const response=await fetch('/api/send/items',{method:'POST',headers:{'X-PhoneHaul-Relative-Path':encodeURIComponent(entry.relativePath)},body:entry.file});if(!response.ok)throw Error((await response.json()).error||'Could not queue file');localPending=localPending.filter(x=>x!==pending)}catch(error){pending.state='failed';pending.error=error.message}renderSend(sendItems,connected)}}
async function fromEntry(entry,prefix=''){if(entry.isFile)return new Promise((resolve,reject)=>entry.file(file=>resolve([{file,relativePath:prefix+file.name}]),reject));if(!entry.isDirectory)return[];const reader=entry.createReader();let children=[];while(true){const batch=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!batch.length)break;children=children.concat(batch)}const nested=await Promise.all(children.map(child=>fromEntry(child,prefix+entry.name+'/')));return nested.flat()}
async function droppedFiles(data){if(data.items&&Array.from(data.items).some(i=>i.webkitGetAsEntry)){const groups=await Promise.all(Array.from(data.items).filter(i=>i.kind==='file').map(i=>{const entry=i.webkitGetAsEntry();return entry?fromEntry(entry):Promise.resolve(i.getAsFile()? [{file:i.getAsFile(),relativePath:i.getAsFile().name}]:[])}));return groups.flat()}return Array.from(data.files).map(file=>({file,relativePath:file.name}))}
const drop=$('drop');drop.onclick=()=>$('sendFiles').click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('sendFiles').click()}};$('chooseFiles').onclick=()=>$('sendFiles').click();$('chooseFolder').onclick=()=>$('sendFolder').click();for(const id of ['sendFiles','sendFolder'])$(id).onchange=e=>{enqueueFiles(Array.from(e.target.files).map(file=>({file,relativePath:file.webkitRelativePath||file.name})));e.target.value=''};drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=async e=>{e.preventDefault();drop.classList.remove('dragging');try{await enqueueFiles(await droppedFiles(e.dataTransfer))}catch(error){$('error').textContent=error.message}};
function render(t,connected){current=t;if(!t){$('state').textContent=connected?'Connected':'Ready to receive';$('description').textContent=connected?'Waiting for files…':'Phone and computer must be connected to the same local network.';$('transfer').hidden=true;return}
 $('state').textContent=t.cancelled?'Transfer cancelled':t.finished?(t.completedItems===t.totalItems?'Transfer complete':'Transfer finished with files left on phone'):'Receiving files';$('description').textContent=t.finished?'Saved to '+$('destination').textContent:'PhoneHaul works only on the same local network.';$('transfer').hidden=false;$('counts').textContent=t.completedItems+' / '+t.totalItems+' files received or already identical';$('bar').value=t.totalBytes?100*t.receivedBytes/t.totalBytes:100;$('bytes').textContent=fmt(t.receivedBytes)+' / '+fmt(t.totalBytes);$('current').textContent=t.currentItem?'Current: '+t.currentItem:'';$('elapsed').textContent='Elapsed: '+Math.floor((Date.now()-t.startedAt)/1000)+' s';$('cancel').hidden=t.finished}
$('change').onclick=()=>{$('settings').style.display=$('settings').style.display==='block'?'none':'block'};
$('save').onclick=async()=>{try{await api('/api/settings','POST',{destination:$('folder').value,conflict:$('conflict').value});$('error').textContent='';$('settings').style.display='none';await load()}catch(e){$('error').textContent=e.message}};
$('refresh').onclick=async()=>{try{await api('/api/qr/refresh','POST');await load()}catch(e){$('error').textContent=e.message}};
$('cancel').onclick=async()=>{if(current)await api('/api/transfers/'+current.transferId+'/cancel','POST');await load()};
$('removePartials').onclick=async()=>{await api('/api/partials/remove','POST');await load()};
const heartbeat=()=>fetch('/api/heartbeat',{method:'POST',cache:'no-store'}).catch(()=>{});
heartbeat();setInterval(heartbeat,5000);
new EventSource('/api/events').onmessage=e=>{const s=JSON.parse(e.data);if(pairingVersion!==s.pairingVersion)load().catch(e=>$('error').textContent=e.message);render(s.transfer,s.connected);renderSend(s.sendQueue,s.sendConnected,s.connected);$('qr').hidden=s.pairingComplete;$('refresh').hidden=s.connected;$('pairText').textContent=s.pairingComplete?(s.connected?'Phone paired. The QR code is hidden.':'Phone paired but not currently connected. Generate a new code to pair again.'):'Scan this QR code with PhoneHaul on your Android phone. It refreshes automatically every five minutes until a phone connects.'};
load().catch(e=>$('error').textContent=e.message);
</script></html>`; }
